version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - /root/promtailloki/loki:/etc/loki
    command: -config.file=/opt/evaluate-loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/log:/var/log
      - /root/promtailloki/promtail:/etc/promtail 
    command: -config.file=/opt/evaluate-loki/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:9.5.1
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - loki